[metadata]
name = ImSwitch
version = attr: imswitch.__version__
author = Xavier Casas Moreno
author_email = xaviercm@kth.se
description = Microscopy control
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/kasasxav/ImSwitch
project_urls =
    Bug Tracker = https://github.com/kasasxav/ImSwitch/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
    Operating System :: OS Independent

[options]
packages = find:
include_package_data = True
python_requires = >=3.10
install_requires =
    coloredlogs>=15
    colour-science>=0.3
    dataclasses-json>=0.5
    fastapi>=0.86
    h5py>=3.0
    luddite>=1.0
    matplotlib>=3.6
    napari>=0.4.17
    numpy>=1.21
    ome-zarr>=0.6
    Pillow>=9.0
    psutil>=5.8
    Pyro5>=5.14
    PyQt5>=5.15
    pyqtgraph>=0.12
    QScintilla>=2.12
    pyserial>=3.4
    QDarkStyle>=3.0
    qtpy>=2.0
    requests>=2.25
    scikit-image>=0.19
    scipy>=1.7
    Send2Trash>=1.8
    pint>=0.20
    setuptools>=42,<80
    tifffile>=2022
    uvicorn[standard]>=0.19
    vispy>=0.11
    zarr>=2.10

[options.extras_require]
hardware =
    nidaqmx>=0.9
    pylablib>=1.4
    pyvisa>=1.12
    pyvisa-py>=0.6
    microscope
    thorlabs_tsi_sdk
full =
    opencv-python>=4.5
test =
    pytest>=7
    pytest-qt>=4
    pytest-cov>=4

[options.entry_points]
console_scripts =
    imswitch = imswitch.__main__:main
