"""Generic time-resolved detector contracts and helpers."""

from .detector_contract import TimeResolvedDetectorMixin
from .io import (
    FORMAT_VERSION,
    load_gate_preset,
    load_products,
    save_gate_preset,
    save_h5,
    save_npz,
    save_tiffs,
)
from .processing import (
    PILEUP_RED,
    PILEUP_WARN,
    TCSPC_DIRECTIONS,
    aggregate_decay,
    background_per_bin,
    compute_gate_images,
    estimate_prepulse_background,
    intensity_from_cube,
    orient_cube,
    pileup_fraction,
    resolve_gates,
    roll_to_peak,
    subtract_background,
    validate_gates,
)
from .types import (
    GATE_REFERENCES,
    GateSpec,
    LifetimeFitConfig,
    LiveProducts,
    TimeResolvedScanConfig,
    TimeResolvedScanProducts,
    copy_time_resolved_products,
)

__all__ = [
    "GATE_REFERENCES",
    "save_tiffs",
    "save_npz",
    "save_h5",
    "save_gate_preset",
    "load_products",
    "load_gate_preset",
    "FORMAT_VERSION",
    "GateSpec",
    "LifetimeFitConfig",
    "LiveProducts",
    "PILEUP_RED",
    "PILEUP_WARN",
    "TCSPC_DIRECTIONS",
    "TimeResolvedDetectorMixin",
    "TimeResolvedScanConfig",
    "TimeResolvedScanProducts",
    "aggregate_decay",
    "background_per_bin",
    "compute_gate_images",
    "copy_time_resolved_products",
    "estimate_prepulse_background",
    "intensity_from_cube",
    "orient_cube",
    "pileup_fraction",
    "resolve_gates",
    "roll_to_peak",
    "subtract_background",
    "validate_gates",
]
