"""Regenerate imswitch/_data/user_defaults_history.json.

    python tools/update_user_defaults_history.py

ImSwitch copies imswitch/_data/user_defaults into the user folder
(~/ImSwitchConfig) and, at every start, replaces a copy that is an older
*shipped* version of a default with the current one, while keeping copies
the user edited (imcommon/model/dirtools.py, syncUserDefaults). Telling the
two apart needs the hash of every version ImSwitch has shipped of every
default file; this collects them from the git history of HEAD plus the
working tree, and writes them.

Run it after changing, adding, moving or removing a default file and commit
the result. imcommon/_test/test_user_defaults_sync.py fails until you do.
"""

import importlib.util
import json
import subprocess
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DEFAULTS = 'imswitch/_data/user_defaults'
OUTPUT = REPO / 'imswitch' / '_data' / 'user_defaults_history.json'


def _dirtools():
    # By path: importing imswitch.imcommon.model pulls in the whole package.
    spec = importlib.util.spec_from_file_location(
        'dirtools', REPO / 'imswitch' / 'imcommon' / 'model' / 'dirtools.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _git(*args, **kwargs):
    return subprocess.run(['git', '-C', str(REPO), *args], check=True,
                          capture_output=True, **kwargs).stdout


def _historicBlobs():
    """(relative path, blob id) for every version of every file under DEFAULTS
    in the history of HEAD, merges included."""
    log = _git('log', '--raw', '--no-abbrev', '-m', '--format=', '--', DEFAULTS, text=True)
    blobs = set()
    for line in log.splitlines():
        if not line.startswith(':'):
            continue
        meta, *paths = line.split('\t')
        newBlob, status = meta.split()[3], meta.split()[4]
        if status.startswith('D') or set(newBlob) == {'0'}:
            continue
        path = paths[-1]
        if path.startswith(DEFAULTS + '/'):
            blobs.add((path[len(DEFAULTS) + 1:], newBlob))
    return blobs


def _blobContents(blobIds):
    """{blob id: bytes}, read with one git cat-file --batch."""
    ids = sorted(blobIds)
    out = _git('cat-file', '--batch', input=''.join(i + '\n' for i in ids).encode())
    contents, position = {}, 0
    for blobId in ids:
        header_end = out.index(b'\n', position)
        size = int(out[position:header_end].split()[2])
        start = header_end + 1
        contents[blobId] = out[start:start + size]
        position = start + size + 1           # the blob is followed by '\n'
    return contents


def main():
    dirtools = _dirtools()
    hashes = defaultdict(set)

    blobs = _historicBlobs()
    contents = _blobContents({blobId for _path, blobId in blobs})
    for relativePath, blobId in blobs:
        if dirtools.isShippedDefault(relativePath):
            hashes[relativePath].add(dirtools.defaultContentHash(contents[blobId]))

    root = REPO / DEFAULTS
    for path in root.rglob('*'):
        relativePath = path.relative_to(root).as_posix()
        if path.is_file() and dirtools.isShippedDefault(relativePath):
            hashes[relativePath].add(dirtools.defaultFileHash(path))

    OUTPUT.write_text(json.dumps({
        '_comment': 'sha256 (CRLF normalised) of every version ever shipped of each '
                    'file in imswitch/_data/user_defaults. Generated by '
                    'tools/update_user_defaults_history.py -- do not edit.',
        'files': {path: sorted(hashes[path]) for path in sorted(hashes)},
    }, indent=1) + '\n', encoding='utf-8')
    total = sum(len(v) for v in hashes.values())
    print(f'{OUTPUT.relative_to(REPO)}: {len(hashes)} files, {total} versions')


if __name__ == '__main__':
    main()
