"""Export a LocalizationResult to the napari-storm (Picasso) HDF5 format.

napari-storm (``napari-storm/napari-storm``) ingests Picasso-style HDF5
files through ``StormDataClass.load_locs`` / ``load_hdf5``: an HDF5 dataset
named ``"locs"`` holding a structured array whose fields are read *by name*
(``frame``, ``x``, ``y``, optional ``z``, ``lpx``/``lpy``/``lpz``, ``photons``),
plus a Picasso ``.yaml`` info sidecar. This module writes exactly that so the
two projects interoperate without a code dependency.

Boundary contract (documented here so it stays stable — see also the port
plan, Phase 4):

* **Lateral positions/precisions are in pixels.** ``x``/``y`` = nm / pixel
  size; ``lpx``/``lpy`` likewise. napari-storm multiplies back by the pixel
  size it is told at import time.
* **z is in nanometres.** ``load_hdf5`` divides ``z`` by the pixel size to get
  pixels, so we must hand it nm.
* **Presence of ``z`` marks 3D.** A 2D export omits ``z``/``lpz`` entirely, so
  napari-storm treats it as planar.
* **``lpx``/``lpy`` carry the fitted PSF sigma** (the canonical schema has no
  separate localization-precision column). This mirrors napari-storm's own
  save path, which derives precision from uncertainty.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from imswitch.improcess.model.localization_result import LocalizationResult


def _picasso_dtype(dims: str) -> np.dtype:
    #: ``sx``/``sy`` are the PSF widths and ``lpx``/``lpy`` the localization
    #: precisions — separate columns in Picasso, and separate here too.
    fields = [("frame", "i4"), ("x", "f4"), ("y", "f4"),
              ("photons", "f4"), ("sx", "f4"), ("sy", "f4"),
              ("lpx", "f4"), ("lpy", "f4")]
    if dims == "3D":
        fields += [("z", "f4"), ("sz", "f4"), ("lpz", "f4")]
    return np.dtype(fields)


def to_picasso_recarray(result: LocalizationResult) -> np.recarray:
    """Build the Picasso ``locs`` recarray for ``result`` (pixels; z in nm)."""
    locs = result.locs
    pixel = result.pixel_size_nm
    out = np.zeros(len(locs), dtype=_picasso_dtype(result.dims)).view(np.recarray)
    out.frame = locs.frame
    out.x = locs.x_nm / pixel
    out.y = locs.y_nm / pixel
    out.photons = locs.photons
    out.sx = locs.sigma_x_nm / pixel
    out.sy = locs.sigma_y_nm / pixel
    out.lpx = locs.lp_x_nm / pixel
    out.lpy = locs.lp_y_nm / pixel
    if result.dims == "3D":
        out.z = locs.z_nm  # nm on purpose (napari-storm divides by pixel size)
        out.sz = locs.sigma_z_nm / pixel
        out.lpz = locs.lp_z_nm / pixel
    return out


def _picasso_info(result: LocalizationResult) -> list[dict]:
    frames = int(result.locs.frame.max()) + 1 if result.count else 0
    height = width = None
    if result.source_shape is not None:
        height, width = (int(result.source_shape[0]), int(result.source_shape[1]))
    info = {
        "Byte Order": "<",
        "Generated by": "ImSwitch ImProcess SMLM export",
        "Pixelsize": float(result.pixel_size_nm),
        "Frames": frames,
    }
    if height is not None:
        info["Height"] = height
        info["Width"] = width
    return [info]


def export_picasso_hdf5(result: LocalizationResult, path: Path) -> Path:
    """Write ``result`` as a Picasso/napari-storm ``.hdf5`` + ``.yaml`` pair.

    Returns the HDF5 path actually written.
    """
    import h5py

    path = Path(path)
    if path.suffix.lower() not in (".hdf5", ".h5"):
        path = path.with_suffix(".hdf5")

    recs = to_picasso_recarray(result)
    with h5py.File(str(path), "w") as h5:
        h5.create_dataset("locs", data=recs)
        # Convenience attrs (napari-storm prompts for pixel size, but we record
        # it here too so the file is self-describing).
        h5["locs"].attrs["pixelsize_nm"] = float(result.pixel_size_nm)
        h5["locs"].attrs["zdim_present"] = result.dims == "3D"

    _write_info_yaml(path, _picasso_info(result))
    return path


def _write_info_yaml(path: Path, info: list[dict]) -> None:
    yaml_path = Path(path).with_suffix(".yaml")
    try:
        import yaml

        with open(yaml_path, "w") as handle:
            yaml.dump_all(info, handle, default_flow_style=False)
    except Exception:
        # The Picasso sidecar is optional for napari-storm's reader (it catches
        # a missing file); never fail the export on the metadata sidecar.
        pass


def read_picasso_hdf5(path: Path, *, pixel_size_nm: float | None = None,
                      name: str | None = None) -> LocalizationResult:
    """Read a Picasso/napari-storm HDF5 back into a canonical result.

    Mirrors napari-storm's field mapping (``load_locs`` + ``load_hdf5``) so the
    export can be round-trip verified without importing napari-storm. The pixel
    size is taken from ``pixel_size_nm``, else the ``locs`` attrs, else the
    ``.yaml`` sidecar's ``Pixelsize``.
    """
    import h5py

    from imswitch.improcess.model.localization_schema import localizations_from_columns

    path = Path(path)
    with h5py.File(str(path), "r") as h5:
        recs = np.rec.array(h5["locs"][...])
        attr_pixel = h5["locs"].attrs.get("pixelsize_nm")

    if pixel_size_nm is None:
        pixel_size_nm = attr_pixel
    if pixel_size_nm is None:
        pixel_size_nm = _read_pixelsize_yaml(path)
    if pixel_size_nm is None:
        raise ValueError("Pixel size unknown; pass pixel_size_nm explicitly")
    pixel_size_nm = float(pixel_size_nm)

    has_z = "z" in recs.dtype.names
    columns = {
        "frame": np.asarray(recs.frame, dtype=np.int32),
        "x_nm": np.asarray(recs.x, dtype=np.float32) * pixel_size_nm,
        "y_nm": np.asarray(recs.y, dtype=np.float32) * pixel_size_nm,
    }
    if "photons" in recs.dtype.names:
        columns["photons"] = np.asarray(recs.photons, dtype=np.float32)
    # Picasso keeps PSF width (sx/sy) and localization precision (lpx/lpy) as
    # separate columns, and so do we. An earlier revision of this reader mapped
    # lpx onto sigma_x_nm, which made that column mean "precision" for imported
    # data and "PSF width" for anything localized here.
    for storm_name, canonical in (
        ("sx", "sigma_x_nm"),
        ("sy", "sigma_y_nm"),
        ("lpx", "lp_x_nm"),
        ("lpy", "lp_y_nm"),
    ):
        if storm_name in recs.dtype.names:
            columns[canonical] = (
                np.asarray(recs[storm_name], dtype=np.float32) * pixel_size_nm
            )
    if has_z:
        columns["z_nm"] = np.asarray(recs.z, dtype=np.float32)  # already nm
        if "sz" in recs.dtype.names:
            columns["sigma_z_nm"] = np.asarray(recs.sz, dtype=np.float32) * pixel_size_nm
        if "lpz" in recs.dtype.names:
            columns["lp_z_nm"] = np.asarray(recs.lpz, dtype=np.float32) * pixel_size_nm

    locs = localizations_from_columns(columns)
    return LocalizationResult(
        name=name or path.stem,
        locs=locs,
        pixel_size_nm=pixel_size_nm,
        dims="3D" if has_z else "2D",
        source_name=path.name,
    )


def _read_pixelsize_yaml(path: Path) -> float | None:
    yaml_path = Path(path).with_suffix(".yaml")
    if not yaml_path.exists():
        return None
    try:
        import yaml

        with open(yaml_path) as handle:
            for doc in yaml.load_all(handle, Loader=yaml.FullLoader):
                if isinstance(doc, dict) and "Pixelsize" in doc:
                    return float(doc["Pixelsize"])
    except Exception:
        return None
    return None


def open_in_napari_storm(result: LocalizationResult, path: Path | None = None) -> Path:
    """Export ``result`` and open it in napari-storm if installed.

    Import-guarded so napari-storm is never a hard dependency: raises
    ``RuntimeError`` with a clear message when it (or napari) is unavailable.
    Returns the exported file path regardless.
    """
    import tempfile

    if path is None:
        tmp_dir = Path(tempfile.mkdtemp(prefix="imswitch_smlm_"))
        path = tmp_dir / f"{result.name or 'localizations'}.hdf5"
    exported = export_picasso_hdf5(result, path)

    try:
        import napari  # noqa: F401
        import napari_storm  # noqa: F401
    except ImportError as exc:  # pragma: no cover - depends on optional install
        raise RuntimeError(
            "napari-storm is not installed; exported the file to "
            f"{exported} — open it manually in napari-storm."
        ) from exc

    import napari  # pragma: no cover

    viewer = napari.Viewer()  # pragma: no cover
    viewer.open(str(exported), plugin="napari-storm")  # pragma: no cover
    return exported


__all__ = [
    "export_picasso_hdf5",
    "read_picasso_hdf5",
    "to_picasso_recarray",
    "open_in_napari_storm",
]
